version: "3.0"

services:
    db:
      image: mariadb:10.3.24
      environment:
        MYSQL_ROOT_PASSWORD: omeka
        MYSQL_DATABASE: omeka
        MYSQL_USER: omeka
        MYSQL_PASSWORD: omeka

    omeka:
      build: .
      ports:
        - 90:80
      tty: true
      links:
        - db:db